<a href="https://colab.research.google.com/github/moraish/ML_Concepts/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.4.1+cu121'

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [8]:
vector = torch.tensor([3,2])
vector

tensor([3, 2])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
MATRIX = torch.tensor([[1,2,3], [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 3])

In [16]:
VECTOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
VECTOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
VECTOR.ndim

3

In [18]:
VECTOR.shape

torch.Size([1, 3, 3])