<a href="https://colab.research.google.com/github/moraish/ML_Concepts/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.4.1+cu121'

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([3,2])
vector

tensor([3, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[1,2,3], [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
VECTOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
VECTOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
VECTOR.ndim

3

In [14]:
VECTOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [15]:
random_tensor = torch.rand(size=(3,3))
random_tensor

tensor([[0.1335, 0.2767, 0.8230],
        [0.4752, 0.0291, 0.6395],
        [0.4041, 0.0733, 0.0682]])

In [16]:
random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(torch.float32, 2, torch.Size([3, 3]))

In [17]:
zeros = torch.zeros(size=(2,3))
zeros, zeros.ndim

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 2)

In [18]:
ones = torch.ones(size=(2,3,4))
ones, ones.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([2, 3, 4]))

In [19]:
arange_vec = torch.arange(0,10,2)
arange_vec

tensor([0, 2, 4, 6, 8])

In [20]:
zeros_like = torch.zeros_like(arange_vec)
zeros_like

tensor([0, 0, 0, 0, 0])

In [21]:
ones_like = torch.ones_like(arange_vec)
ones_like

tensor([1, 1, 1, 1, 1])

In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [26]:
tensor = torch.tensor([10,20,30])

In [27]:
tensor + 1

tensor([11, 21, 31])

In [28]:
tensor * 10

tensor([100, 200, 300])

In [29]:
tensor - 10

tensor([ 0, 10, 20])

In [30]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [31]:
torch.add(tensor, 5)

tensor([15, 25, 35])

In [32]:
tensor @ tensor # 100, 400, 900

tensor(1400)

In [34]:
torch.matmul(tensor, tensor)

tensor(1400)

In [38]:
tensor_A = torch.tensor([[[1, 2],
                         [3, 4],
                         [5, 6]]], dtype=torch.float32)

tensor_A.shape

torch.Size([1, 3, 2])

In [39]:
tensor

tensor([10, 20, 30])

In [5]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
tensor_A.T

tensor([[1., 3., 5.],
        [2., 4., 6.]])

In [6]:
linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)

x.shape, output.shape

(torch.Size([3, 2]), torch.Size([3, 6]))

In [7]:
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [8]:
output

tensor([[ 0.7762,  1.1924, -0.3635,  0.9028, -1.3197, -2.4060],
        [ 1.5369,  3.0883,  0.5857,  3.0102, -3.8599, -4.7920],
        [ 2.2976,  4.9841,  1.5348,  5.1177, -6.4001, -7.1779]],
       grad_fn=<AddmmBackward0>)

In [9]:
output.max(), output.min(), output.mean(), output.sum()

(tensor(5.1177, grad_fn=<MaxBackward1>),
 tensor(-7.1779, grad_fn=<MinBackward1>),
 tensor(-0.0718, grad_fn=<MeanBackward0>),
 tensor(-1.2923, grad_fn=<SumBackward0>))

In [10]:
torch.max(output), torch.min(output), torch.mean(output), torch.sum(output)

(tensor(5.1177, grad_fn=<MaxBackward1>),
 tensor(-7.1779, grad_fn=<MinBackward1>),
 tensor(-0.0718, grad_fn=<MeanBackward0>),
 tensor(-1.2923, grad_fn=<SumBackward0>))

In [12]:
torch.argmax(output), torch.argmin(output)

(tensor(15), tensor(17))

In [14]:
output.argmax(), output.argmin()

(tensor(15), tensor(17))

In [15]:
tensor = torch.arange(10, 100, 10)
tensor.dtype

torch.int64

In [18]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype, tensor_float16

(torch.float16,
 tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16))

In [27]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [28]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [30]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [32]:
z[:, 5] = 5
z, x

(tensor([[1., 2., 3., 4., 5., 5., 7.]]), tensor([1., 2., 3., 4., 5., 5., 7.]))

In [33]:
x_stacked = torch.stack([x,x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 5., 7.],
         [1., 2., 3., 4., 5., 5., 7.],
         [1., 2., 3., 4., 5., 5., 7.],
         [1., 2., 3., 4., 5., 5., 7.],
         [1., 2., 3., 4., 5., 5., 7.]]),
 torch.Size([5, 7]))

In [36]:
x_stacked = torch.stack([x_reshaped,x_reshaped,x_reshaped,x_reshaped,x_reshaped], dim=0)
x_stacked, x_stacked.shape

(tensor([[[1., 2., 3., 4., 5., 5., 7.]],
 
         [[1., 2., 3., 4., 5., 5., 7.]],
 
         [[1., 2., 3., 4., 5., 5., 7.]],
 
         [[1., 2., 3., 4., 5., 5., 7.]],
 
         [[1., 2., 3., 4., 5., 5., 7.]]]),
 torch.Size([5, 1, 7]))

In [37]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 5., 7.]]), torch.Size([1, 7]))

In [39]:
torch.squeeze(x_reshaped), torch.squeeze(x_reshaped).shape

(tensor([1., 2., 3., 4., 5., 5., 7.]), torch.Size([7]))

In [41]:
torch.squeeze(x_stacked), torch.squeeze(x_stacked).shape

(tensor([[1., 2., 3., 4., 5., 5., 7.],
         [1., 2., 3., 4., 5., 5., 7.],
         [1., 2., 3., 4., 5., 5., 7.],
         [1., 2., 3., 4., 5., 5., 7.],
         [1., 2., 3., 4., 5., 5., 7.]]),
 torch.Size([5, 7]))

In [42]:
x_rand = torch.rand(size=(3,224,224))
x_rand, x_rand.shape

(tensor([[[0.4121, 0.1540, 0.4192,  ..., 0.2901, 0.1496, 0.4730],
          [0.3648, 0.2002, 0.8448,  ..., 0.0048, 0.0172, 0.8793],
          [0.1505, 0.3896, 0.8874,  ..., 0.0801, 0.6156, 0.7624],
          ...,
          [0.7161, 0.7164, 0.1084,  ..., 0.8106, 0.6460, 0.8261],
          [0.7186, 0.2549, 0.5211,  ..., 0.7221, 0.9577, 0.5896],
          [0.7921, 0.4604, 0.1740,  ..., 0.6732, 0.1159, 0.5503]],
 
         [[0.5961, 0.9042, 0.3415,  ..., 0.0252, 0.6126, 0.5362],
          [0.7589, 0.9123, 0.1640,  ..., 0.2105, 0.5298, 0.7109],
          [0.0149, 0.5986, 0.2699,  ..., 0.9683, 0.1451, 0.7802],
          ...,
          [0.0184, 0.2222, 0.2337,  ..., 0.1320, 0.3343, 0.6610],
          [0.5979, 0.7645, 0.9734,  ..., 0.6990, 0.0307, 0.2741],
          [0.6165, 0.6051, 0.9766,  ..., 0.1875, 0.6211, 0.9734]],
 
         [[0.6556, 0.0616, 0.7935,  ..., 0.9740, 0.1714, 0.5274],
          [0.1018, 0.4286, 0.9547,  ..., 0.3926, 0.6145, 0.3821],
          [0.0604, 0.0145, 0.8194,  ...,

In [43]:
x_permuted = x_rand.permute(2,0,1)
x_permuted, x_permuted.shape

(tensor([[[0.4121, 0.3648, 0.1505,  ..., 0.7161, 0.7186, 0.7921],
          [0.5961, 0.7589, 0.0149,  ..., 0.0184, 0.5979, 0.6165],
          [0.6556, 0.1018, 0.0604,  ..., 0.1400, 0.4770, 0.0572]],
 
         [[0.1540, 0.2002, 0.3896,  ..., 0.7164, 0.2549, 0.4604],
          [0.9042, 0.9123, 0.5986,  ..., 0.2222, 0.7645, 0.6051],
          [0.0616, 0.4286, 0.0145,  ..., 0.5491, 0.4431, 0.0889]],
 
         [[0.4192, 0.8448, 0.8874,  ..., 0.1084, 0.5211, 0.1740],
          [0.3415, 0.1640, 0.2699,  ..., 0.2337, 0.9734, 0.9766],
          [0.7935, 0.9547, 0.8194,  ..., 0.3066, 0.3201, 0.1886]],
 
         ...,
 
         [[0.2901, 0.0048, 0.0801,  ..., 0.8106, 0.7221, 0.6732],
          [0.0252, 0.2105, 0.9683,  ..., 0.1320, 0.6990, 0.1875],
          [0.9740, 0.3926, 0.8174,  ..., 0.6152, 0.9682, 0.7203]],
 
         [[0.1496, 0.0172, 0.6156,  ..., 0.6460, 0.9577, 0.1159],
          [0.6126, 0.5298, 0.1451,  ..., 0.3343, 0.0307, 0.6211],
          [0.1714, 0.6145, 0.6173,  ..., 0.1231,

In [44]:
x_stacked

tensor([[[1., 2., 3., 4., 5., 5., 7.]],

        [[1., 2., 3., 4., 5., 5., 7.]],

        [[1., 2., 3., 4., 5., 5., 7.]],

        [[1., 2., 3., 4., 5., 5., 7.]],

        [[1., 2., 3., 4., 5., 5., 7.]]])

In [45]:
x_stacked.shape

torch.Size([5, 1, 7])

In [46]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [47]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x[0][0]

tensor([1, 2, 3])

In [49]:
x[0][0][0]

tensor(1)

In [52]:
x[:,:,1]

tensor([[2, 5, 8]])

In [53]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [54]:
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

False